/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.net.URL;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DELL
 */
public class AddStory extends javax.swing.JFrame {
    
    JFileChooser chooser;

    File f;

    /**
     * Creates new form AddStory
     */
    public AddStory() {
        initComponents();
        
        setSize(1000,900);
    }
    
    String pid;
    String username;

    AddStory(String pid,String username) {
        initComponents();
        this.pid = pid;
        //System.out.println("Story pid"+pid);
        this.username = username;
        setSize(1000, 900);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        chooser=new JFileChooser();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        captionlb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        captionta = new javax.swing.JTextArea();
        photolb = new javax.swing.JLabel();
        choosebtn = new javax.swing.JButton();
        postlb = new javax.swing.JLabel();
        filter1btn = new javax.swing.JButton();
        filter2btn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        picspanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb2.setBackground(new java.awt.Color(255, 153, 153));
        lb2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lb2.setText("ADD POST");
        getContentPane().add(lb2);
        lb2.setBounds(320, 10, 190, 40);

        captionlb.setText("Caption");
        getContentPane().add(captionlb);
        captionlb.setBounds(130, 70, 120, 30);

        captionta.setColumns(20);
        captionta.setRows(5);
        jScrollPane1.setViewportView(captionta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 60, 260, 30);

        photolb.setText("Photo");
        getContentPane().add(photolb);
        photolb.setBounds(130, 100, 160, 50);

        choosebtn.setText("Choose");
        choosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(choosebtn);
        choosebtn.setBounds(400, 100, 110, 40);

        postlb.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(postlb);
        postlb.setBounds(170, 160, 290, 150);

        filter1btn.setText("Filter1");
        getContentPane().add(filter1btn);
        filter1btn.setBounds(580, 160, 100, 40);

        filter2btn.setText("Filter2");
        getContentPane().add(filter2btn);
        filter2btn.setBounds(580, 230, 100, 40);

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn);
        addbtn.setBounds(20, 270, 130, 40);

        lb1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb1.setText("Already Added Pictures");
        getContentPane().add(lb1);
        lb1.setBounds(270, 330, 310, 30);

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn);
        closebtn.setBounds(280, 610, 160, 50);

        picspanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout picspanelLayout = new javax.swing.GroupLayout(picspanel);
        picspanel.setLayout(picspanelLayout);
        picspanelLayout.setHorizontalGroup(
            picspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        picspanelLayout.setVerticalGroup(
            picspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(picspanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 370, 690, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosebtnActionPerformed

        int r = chooser.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            try {

                BufferedImage bimg = ImageIO.read(f);
                Image img = bimg.getScaledInstance(postlb.getWidth(), postlb.getHeight(), Image.SCALE_SMOOTH);
                postlb.setIcon(new ImageIcon(img));

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_choosebtnActionPerformed

    public void showpics(String pid)
    {
        this.pid = pid;
        //System.out.println(pid);
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/showpics")
                    .queryString("pid",pid)
                    .asString();
            
            if (res.getStatus() == 200) 
            {
            int x = 10;
            int mainheight = 100;
            String data = res.getBody();
            StringTokenizer st = new StringTokenizer(data, "$");

            picspanel.removeAll();
            while (st.hasMoreTokens()) {

                String userdata = st.nextToken();
                //System.out.println(userdata);
                StringTokenizer st1 = new StringTokenizer(userdata, ";#");
                String psid  = st1.nextToken();
                String photo = st1.nextToken();
                String caption = st1.nextToken();

                storypanel sp = new storypanel();
                sp.setBounds(x, 10, 300, 300);
                picspanel.add(sp);

                URL url = new URL("http://localhost:8999/GetResource/" + photo);
                BufferedImage bimg = ImageIO.read(url);
                Image img = bimg.getScaledInstance(sp.photolb.getWidth(), sp.photolb.getHeight(), Image.SCALE_SMOOTH);
                sp.photolb.setIcon(new ImageIcon(img));

                sp.captionlb.setText(caption);

                sp.closebtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {

                        try {
                            HttpResponse<String> res = Unirest.get("http://localhost:8999/closeopr")
                                    .queryString("psid", psid)
                                    .asString();

                            if (res.getStatus() == 200) {
                                String responsetext = res.getBody();
                                JOptionPane.showMessageDialog(picspanel, responsetext);
                                showpics(pid);
                            }
                            //System.out.println(user_n);
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        
                        }
                    
                });

                x += 310;
                mainheight += 90;
            }
            
            picspanel.repaint();
            
        }
            
        }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    
        
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            String caption = captionta.getText();

            if (f == null)
            {
                JOptionPane.showMessageDialog(this, "Please choose file");
            }

            else
            {
                HttpResponse<String> res = Unirest.post("http://localhost:8999/addstory")
                .queryString("caption",caption)
                .queryString("pid",pid)
                .field("photo", f)
                .asString();

                if(res.getStatus()==200)
                {
                    JOptionPane.showMessageDialog(this, "Story Added");
                    captionta.setText("");
                    postlb.setIcon(null);
                    showpics(pid);
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStory().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel captionlb;
    private javax.swing.JTextArea captionta;
    private javax.swing.JButton choosebtn;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton filter1btn;
    private javax.swing.JButton filter2btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel photolb;
    private javax.swing.JPanel picspanel;
    private javax.swing.JLabel postlb;
    // End of variables declaration//GEN-END:variables
}
