
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class ForgetPassForm extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassForm
     */
    public ForgetPassForm() {
        initComponents();
        setSize(800,900);
        Panel1.setVisible(true);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }


    String otp;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        otptf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        otpsubmitbtn = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        newpasstf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        confirmpasstf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        changebtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Panel1.setBackground(new java.awt.Color(102, 255, 204));
        Panel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        Panel1.add(jLabel2);
        jLabel2.setBounds(70, 20, 90, 30);
        Panel1.add(usernametf);
        usernametf.setBounds(160, 20, 370, 40);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel3.setText("OTP will be sent to your mobile");
        Panel1.add(jLabel3);
        jLabel3.setBounds(210, 70, 290, 30);

        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        Panel1.add(submitbtn);
        submitbtn.setBounds(260, 120, 180, 40);

        getContentPane().add(Panel1);
        Panel1.setBounds(20, 10, 710, 190);

        Panel2.setBackground(new java.awt.Color(102, 255, 204));
        Panel2.setLayout(null);
        Panel2.add(otptf);
        otptf.setBounds(190, 40, 370, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Enter OTP");
        Panel2.add(jLabel4);
        jLabel4.setBounds(90, 50, 90, 30);

        otpsubmitbtn.setText("Submit");
        otpsubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpsubmitbtnActionPerformed(evt);
            }
        });
        Panel2.add(otpsubmitbtn);
        otpsubmitbtn.setBounds(270, 110, 180, 40);

        getContentPane().add(Panel2);
        Panel2.setBounds(20, 220, 710, 180);

        Panel3.setBackground(new java.awt.Color(102, 255, 204));
        Panel3.setLayout(null);
        Panel3.add(newpasstf);
        newpasstf.setBounds(240, 20, 370, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Enter new password");
        Panel3.add(jLabel5);
        jLabel5.setBounds(60, 30, 160, 40);
        Panel3.add(confirmpasstf);
        confirmpasstf.setBounds(240, 70, 370, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Confirm Password");
        Panel3.add(jLabel6);
        jLabel6.setBounds(70, 80, 130, 30);

        changebtn.setText("Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        Panel3.add(changebtn);
        changebtn.setBounds(280, 130, 180, 40);

        getContentPane().add(Panel3);
        Panel3.setBounds(20, 420, 710, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    String username;
    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        username = usernametf.getText();
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/forgetpassword")
                        .queryString("username", username)
                        .asString();
            
            if(res.getStatus()==200)
            {
                String data = res.getBody();
                StringTokenizer st = new StringTokenizer(data,"#;");
                otp = st.nextToken();
                String ans = st.nextToken();
                if(ans.equals("success"))
                {
                    JOptionPane.showMessageDialog(this, "Username Matched");
                    Panel1.setVisible(false);
                    Panel2.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Username Not Matched");
                    usernametf.setText("");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void otpsubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpsubmitbtnActionPerformed
        String userotp = otptf.getText();
        if(userotp.equals(otp))
        {
            JOptionPane.showMessageDialog(Panel2, "OTP Matched");
            Panel1.setVisible(false);
            Panel2.setVisible(false);
            Panel3.setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(Panel2, "Wrong OTP");
            otptf.setText("");
        }
    }//GEN-LAST:event_otpsubmitbtnActionPerformed

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        String newpass = newpasstf.getText();
        String confirmpass = confirmpasstf.getText();
        if(newpass.equals(confirmpass))
        {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/changepassword")
                        .queryString("username", username)
                        .queryString("newpass",newpass)
                        .asString();
                
                if(res.getStatus()==200)
                {
                    String responseText = res.getBody();
                    JOptionPane.showMessageDialog(this, responseText);
                    dispose();
                    new UserLogin().setVisible(true);
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Password Didn't Matched");
            newpasstf.setText("");
            confirmpasstf.setText("");
        }
    }//GEN-LAST:event_changebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel1;
    public javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JButton changebtn;
    public javax.swing.JTextField confirmpasstf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField newpasstf;
    private javax.swing.JButton otpsubmitbtn;
    private javax.swing.JTextField otptf;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
