/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class ShowCommentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowCommentPanel
     */
    public ShowCommentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cphotolb = new javax.swing.JLabel();
        usernamelb = new javax.swing.JLabel();
        commentlb = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(null);

        cphotolb.setBackground(new java.awt.Color(255, 255, 255));
        cphotolb.setText("photo");
        add(cphotolb);
        cphotolb.setBounds(600, 10, 60, 60);

        usernamelb.setText("username");
        add(usernamelb);
        usernamelb.setBounds(480, 50, 110, 30);

        commentlb.setText("comment");
        add(commentlb);
        commentlb.setBounds(10, 10, 530, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel commentlb;
    public javax.swing.JLabel cphotolb;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel usernamelb;
    // End of variables declaration//GEN-END:variables
}
