/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class storypanel extends javax.swing.JPanel {

    /**
     * Creates new form storypanel
     */
    public storypanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        captionlb = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(null);

        captionlb.setBackground(new java.awt.Color(255, 255, 204));
        add(captionlb);
        captionlb.setBounds(10, 160, 190, 60);
        add(photolb);
        photolb.setBounds(20, 30, 150, 110);

        closebtn.setText("X");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        add(closebtn);
        closebtn.setBounds(200, 10, 40, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel captionlb;
    public javax.swing.JButton closebtn;
    public javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
