/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class userpanel extends javax.swing.JPanel {

    /**
     * Creates new form userpanel
     */
    public userpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photolb = new javax.swing.JLabel();
        usernamelb = new javax.swing.JLabel();
        followbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setLayout(null);

        photolb.setText("photo");
        add(photolb);
        photolb.setBounds(10, 20, 70, 50);

        usernamelb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usernamelb.setText("username");
        add(usernamelb);
        usernamelb.setBounds(100, 10, 140, 30);

        followbtn.setText("Follow");
        followbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followbtnActionPerformed(evt);
            }
        });
        add(followbtn);
        followbtn.setBounds(250, 30, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void followbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_followbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton followbtn;
    public javax.swing.JLabel photolb;
    public javax.swing.JLabel usernamelb;
    // End of variables declaration//GEN-END:variables
}
