
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class UserLogin extends javax.swing.JFrame {
    
    String username;

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
       
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        getContentPane().setBackground(new Color(255,204,204));
        int width = (int)size.getWidth();
        int height = (int)size.getHeight();
        setSize(width,height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        fpasslb = new javax.swing.JLabel();
        returnbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 30, 110, 30);
        getContentPane().add(usernametf);
        usernametf.setBounds(640, 170, 220, 40);

        lb2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb2.setText("Enter Username");
        getContentPane().add(lb2);
        lb2.setBounds(470, 180, 160, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 250, 150, 30);
        getContentPane().add(passwordtf);
        passwordtf.setBounds(640, 250, 220, 40);

        loginbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(590, 330, 160, 50);

        fpasslb.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fpasslb.setText("Forgot Password ?");
        fpasslb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpasslbMouseClicked(evt);
            }
        });
        getContentPane().add(fpasslb);
        fpasslb.setBounds(600, 390, 140, 30);

        returnbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnbtn.setText("<---");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnbtn);
        returnbtn.setBounds(20, 20, 70, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed

        try {

            username = usernametf.getText();
            String password = passwordtf.getText();

            if (username.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            } 
            
            
            else if(evt.getSource().equals(fpasslb))
            {
                
            }
            
            else 
            {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/userlogin")
                        .queryString("username", username)
                        .queryString("password", password)
                        .asString();
                if (res.getStatus() == 200) {
                    String responsetext = res.getBody();
                    JOptionPane.showMessageDialog(this, responsetext);

                    if (responsetext.equals("success")) {

                        new Userhome(username).setVisible(true);
                        dispose();
                    } else {

                    }

                }
            }
            

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_loginbtnActionPerformed

    private void fpasslbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpasslbMouseClicked
        fpasslb.addMouseListener(new MouseAdapter() {
                            @Override
                            public void mouseClicked(MouseEvent me) {
                                super.mouseClicked(me); 
                                dispose();
                                new ForgetPassForm().setVisible(true);
                                
                            }

                        });
    }//GEN-LAST:event_fpasslbMouseClicked

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        dispose();
        new ProjectMainPage().setVisible(true);
    }//GEN-LAST:event_returnbtnActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fpasslb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JButton returnbtn;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
