
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Wallpanel extends javax.swing.JPanel {

    /**
     * Creates new form Wallpanel
     */
    public Wallpanel() {
        initComponents();
//        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
//        int width = (int)size.getWidth();
//        int height = (int)size.getHeight();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postlb = new javax.swing.JLabel();
        titlelb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        likeslb = new javax.swing.JLabel();
        likebtn = new javax.swing.JButton();
        datelb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        usernamelb = new javax.swing.JLabel();
        commenttf = new javax.swing.JTextField();
        commentbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentpanel = new javax.swing.JPanel();

        setLayout(null);

        postlb.setBackground(new java.awt.Color(255, 255, 255));
        postlb.setText("post");
        add(postlb);
        postlb.setBounds(30, 60, 390, 230);

        titlelb.setText("title");
        add(titlelb);
        titlelb.setBounds(60, 290, 390, 50);

        jLabel3.setText("Title");
        add(jLabel3);
        jLabel3.setBounds(10, 300, 50, 30);

        likeslb.setText("likes");
        add(likeslb);
        likeslb.setBounds(450, 210, 40, 30);

        likebtn.setText("Like");
        likebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likebtnActionPerformed(evt);
            }
        });
        add(likebtn);
        likebtn.setBounds(430, 250, 70, 30);

        datelb.setText("date");
        add(datelb);
        datelb.setBounds(360, 20, 130, 30);

        jLabel6.setText("Date");
        add(jLabel6);
        jLabel6.setBounds(300, 30, 30, 20);

        photolb.setText("user_phot");
        add(photolb);
        photolb.setBounds(20, 20, 60, 40);

        usernamelb.setText("user_name");
        add(usernamelb);
        usernamelb.setBounds(100, 20, 160, 40);
        add(commenttf);
        commenttf.setBounds(10, 340, 380, 30);

        commentbtn.setText("Comment");
        commentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentbtnActionPerformed(evt);
            }
        });
        add(commentbtn);
        commentbtn.setBounds(390, 340, 100, 30);

        commentpanel.setBackground(new java.awt.Color(255, 255, 255));
        commentpanel.setLayout(null);
        jScrollPane1.setViewportView(commentpanel);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 500, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void likebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likebtnActionPerformed

    private void commentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentbtnActionPerformed
        
    }//GEN-LAST:event_commentbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton commentbtn;
    public javax.swing.JPanel commentpanel;
    public javax.swing.JTextField commenttf;
    public javax.swing.JLabel datelb;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton likebtn;
    public javax.swing.JLabel likeslb;
    public javax.swing.JLabel photolb;
    public javax.swing.JLabel postlb;
    public javax.swing.JLabel titlelb;
    public javax.swing.JLabel usernamelb;
    // End of variables declaration//GEN-END:variables
}
